# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 015902d762849f3ff1ed0bb74797f90e7a2674aedae32a20d6a4ba81dc7cc3a08c20b6646628c41350d556b64fbb0f79959775cb20d6e38a8df325223cbaf71b

test:
  secret_key_base: bee780bf3d16807941dce5d0034472b4fabf5823fd36ef5d3cf7f1d1e0f1ae9bb38438b383aad4a9ad782e75375dcbb658c63e96183839f21a158722096d72ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
